### ISSUE TITLE
English dialogs: chores

### ISSUE THREAD

**Issue by christopho** [solarus-games/zelda-xd2-mercuris-chess#105]

**Comment by Diarandor** [comment]
Commited here https://github.com/solarus-games/zelda-xd2-mercuris-chess/commit/307693750db49076a1be87cfe038e607630020ce
Check the translation labels, there are things missing.

**Comment by christopho** [comment]
@Diarandor what do you mean with translation labels?
Missing things should be listed here: https://github.com/solarus-games/zelda-xd2-mercuris-chess/issues/125
