### ISSUE TITLE
Weird behavior of separators in creeper cave

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/zelda-xd2-mercuris-chess#12]
In a cave with creepers (I don't remember which one, but I think there was a creeper face drawn on the ground), separators have weird behavior (maybe they are too close?).

**Comment by christopho** [comment]
Duplicate of #1, already fixed

**Comment by Diarandor** [comment]
Whoops, I didn't see it since the issue was already fixed and closed.

**Comment by christopho** [comment]
No problem! :)
