### ISSUE TITLE
English translation: miscellaneous remarks

### ISSUE THREAD

**Issue by Morwenn** [solarus-games/zelda-xd2-mercuris-chess#124]
A few miscellaneous notes about the English translation:

- [x] `text{ key = "inventory.caption.item.lamp.1", value = "Lanp" }` -> Lamp
- [x] `text{ key = "selection_menu.phase.erase_file", value = "Select File to Erase" }` and `text{ key = "selection_menu.phase.select_file", value = "Select a file" }` should probably have the same capitalization
- [x] `Now is not a good time to put on some perfume` -> lacks a final dot
- [x] `You found a Fairy, that's cool!` -> `pretty cool!` sounds better IMHO :p
- [x] `You found a fairy!` -> `Fairy` lacks a capital
- [x] `Everything is allright` -> either `alright` or `all right`
- [x] `Well, I hope.` -> `Well, I hope so.` would probaby sound more natural
- [x] `of time and space itself!` -> itself for two elements? I'm not sure what to put here
- [x] `But let's leave from this place` -> I thing we can get rid of the `from`

That's all for now, I might complete the list later :)

---

Second batch of comments (question marks when I'm not sure, take most things as suggestions, I'm not an actual reference):

- [x] We are supposed to be arrived.  -> to have arrived (?)
- [x] Are we really at the right place?  -> Is this really the right place?
- [x] It must be the one who lead -> which(?) leads
- [x] As a first task, -> For your first task,
- [x] It's name is Snowflake -> Its name
- [x] I command you to cut al those weeds [...] -> all those weeds
- [x] Now, you must bring me my mail.  -> /s/must/shall could be fun
- [x] because the mail -> "for the mail" could be fun too :p
- [x] He never wants to send me the Permit A38!  -> "He always refused to [...], "the Permit" or just "Permit"? I'm unsure which sounds better
- [x] I'm in holidays at Delfino -> I'm on holiday in Delfino (assuming Delfino is a place and not somebody's name)
- [x] How dare you leaving just like that? -> How dare you leave

**Comment by christopho** [comment]
Thanks!
Keeping the issue open, you can add more notes later here.

**Comment by Morwenn** [comment]
Thanks for everything, I'll be in Japan tomorrow yet I still think about you. Good luck for everything :)
