### ISSUE TITLE
English translation: find replacements to French culture references

### ISSUE THREAD

**Issue by christopho** [solarus-games/zelda-xd2-mercuris-chess#125]
A lot of dialogs are hard to translate because they are references to French movies or French TV shows that are famous only in France. This issue keeps tracks of them in order to discuss solutions for them later.

Feel free to comment this issue with any suggestion of US or UK culture references that might be used a replacements, even if jokes will be completely different. We don't want exact translations, we want alternative references.

- [x] chores.chore_2_thanks_1: "Merci le gueux, t'es un laideron mais t'es bien bon !" (French movie Les Visiteurs). -> @oclero said: It should be translated by some kind of arrogant stuff from the princess towards Link, since he's not part of royalty
- [x] chores.chore_2_thanks_3
- [x] island.grump_tower_guard_2
- [x] island.shop.flippers
- [x] island.shop.kitchen
- [x] island.shop.laboratory
- [x] final.zelda_1: "coup de Fatal-foudre"
- [x] dungeon_1.1f.julien_dore
- [x] lafoo_riot.npc_9
- [x] lafoo_riot.npc_10

Check for Morwenn comments around the commits of:
- [x] desert
- [x] main_village
- [x] island

**Comment by oclero** [comment]
Julien Doré -> Justien Bieber
