### ISSUE TITLE
English translation: some typos

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/zelda-xd2-mercuris-chess#130]
I will update this list when I find more:

Important typos:
- [x] "Level 2 Castle of Alternative Truth" -> Should be "Level 1"! (when you enter the dungeon)
-----
Random stuff:
- [x] "I think they went there to demonstrate **there** anger." -> "their".
- [x] "frakking" -> "fracking"???
- [x] "...except that **it** more about lightning rather..." -> "it's"
- [x] "otheriwse" -> "otherwise"
- [x] "Did you spend **to** whole day..." -> "the"
- [x] "Yoo too" -> ??? and "you weight" -> your. (lava challenge dialog)
- [x] "I've **open** up this club" -> "opened"; "it has a good success" -> "it has been a success"; "I invite you to tests" -> "to test". (Ganon's dialog)
------
Library:
- [x] "no bird **are** allowed" -> "is"
- [x] "you DO NOT talk **abou**" -> "about"
- [x] "perursor" -> "precursor"???
- [x] "ripost" -> ???; "because news Cuccos" -> "new".
- [x] "an Hylian" -> "a Hylian"
- [x] "I did not saw in him a monster" -> "I did not see a monster in him"; "forgive-me" -> "forgive me".
- [x] "passed thru" -> "passed through"
- [x] "to talk my" -> "to talk to me"
-------
More random stuff:
- [x] "with too much" -> "too much"
- [x] "iPlume" -> "iFeather"

**Comment by christopho** [comment]
Fixed and released in 1.0.6
