### ISSUE TITLE
Chess enemies not created in a room sometimes

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/zelda-xd2-mercuris-chess#14]
Chess enemies are not created in a room sometimes.
The room is in Grump tower, floor 4, down-left room: if you enter this room from the right door (just after coming dowm from floor 5), then the chess enemies are not created and do not appear in this room. However they do appear if you enter from the upper door. Is this intentional or a bug?

**Comment by christopho** [comment]
Already fixed by edd2b2b
