### ISSUE TITLE
Mis-placed items with higher resolution

### ISSUE THREAD

**Issue by MetalES** [solarus-games/zelda-xd2-mercuris-chess#20]
![sans titre 2](https://cloud.githubusercontent.com/assets/4288633/24590910/1b5be37c-17f6-11e7-87d0-5b38c3965f78.png)

I love this game, eve if it's a april fool there's a lot of efforts put into it, however, i like playing with higher resolution because I have a 16:10 screen, this happen.
This also happen in the inventory menu.

**Comment by christopho** [comment]
But the game is only designed for 320x240. Allowing larger quest sizes will also break separators between rooms.

**Comment by Diarandor** [comment]
Would it be possible to make separators independent from resolution?
We could open a new issue for this in the engine repo.

**Comment by christopho** [comment]
What do you mean? All rooms in this game have a size of 320x240 and if the camera is bigger, separators cannot be respected.

**Comment by Diarandor** [comment]
I have never used separators so I don't know exactly how they work. But maybe displaying in black what is to the other side could work; but this behavior might be weird and it would not be the same, so maybe better to forget about this.

**Comment by christopho** [comment]
But with black bars it becomes equivalent to playing with the resolution 320x240.

**Comment by Diarandor** [comment]
Ok, forget about this then.

**Comment by MetalES** [comment]
Oh this is why there s a lot of problems in the second dungeon
