### ISSUE TITLE
Replace custom lift for cannonball with a better one

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/zelda-xd2-mercuris-chess#21]
Replace custom lift for cannonball with a better one:
-use custom entities instead of destructibles
-adapt the script to the multi events script to make it as independent as possible

This would allow to avoid all the bugs related to the cannonball.

**Comment by Diarandor** [comment]
In the end we will be using destructibles with modifications in the carried_object metatable to allow customizations. But I am having a problem to make the iron ball traversable:
https://github.com/solarus-games/solarus/issues/1045

Could this be fixed before the next bugfix of ZS-XD2?

**Comment by Diarandor** [comment]
I updated the iron ball with the new version (check the new version of the script for the metatable of carried objects). The new iron ball does not get stuck in walls!!! During the falling trajectory a custom entity is used, which is replaced by a destructible again after falling.

Remark: the script is short and allows a lot of easy customization. The path of the sprite has to be of the form "portables/" .. TYPE .. "filename", where TYPE is a string of the form "type/subtype1/subtype2/..." with as many subtypes as needed (if TYPE is "" then the default properties are used).  The types/subtypes can be used to choose how to modify the properties of the falling trajectory (a casewise function of the script has to be modified for this purpose).

**Comment by Diarandor** [comment]
-Don't forget about the bug I mentioned above. The iron ball is still not traversable, so the hero may get stuck with the ball, which is very annoying.

-I haven't tried to test what happens when throwing the new iron ball into water, but probably there will be some problem (I think I forgot to add some sprites for the ground effects that are necessary in that case for the splash animation in water, and probably the sound too). If so, open a new issue and I will add what is needed.

**Comment by Diarandor** [comment]
Workaround for the first bug (of the hero getting stuck with the iron ball): just wait until the hero is not overlapping the custom entity (used during the throw) before creating the destructible.

**Comment by christopho** [comment]
There is an easy way to modify the ground even when an entity has no "set_modified_ground" method: just add another entity above that supports modifying the ground.

And ZSXD2 already has some custom entity models whose only purpose is to modify the ground.

So as a workaround for the ground issue, you can put a custom entity with model "traversable" while the hero is overlapping the destructible iron ball. Just to allow the hero to get out of the iron ball. And with a timer, remove that custom entity as soon as the hero is no longer overlapping.
